name: Sync to Gitee

on:
  workflow_dispatch:
  schedule:
    - cron: '45 6 * * *'
  #push:

jobs:
  run:
    if: ${{ github.repository_owner == 'Glavo' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup SSH
        run: |
          mkdir -p ~/gitee/.ssh
          echo "$INPUT_SSH_PRIVATE_KEY" > ~/gitee/.ssh/id_rsa
          chmod 600 ~/gitee/.ssh/id_rsa
        env:
          INPUT_SSH_PRIVATE_KEY:
            ${{ secrets.GITEE_SYNC_BOT_PRIVATE_KEY }}
      - name: Sync to Gitee
        run: |
          export GIT_SSH_COMMAND="ssh -v -i ~/gitee/.ssh/id_rsa -o StrictHostKeyChecking=no -F /dev/null"
          git remote add mirror "$INPUT_TARGET_REPO_URL"
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
        env:
          INPUT_TARGET_REPO_URL:
            git@gitee.com:Glavo/HMCL-Update.git