name: Sync to Gitee

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ['Update version JSON', 'Update README']
    types:
      - completed

jobs:
  run:
    if: ${{ github.repository_owner == 'Glavo' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitee.com:Glavo/HMCL-Update.git
          ssh_private_key:
            ${{ secrets.GITEE_SYNC_BOT_PRIVATE_KEY }}
