name: Update README
on:
  push:
    branches:
      - main
    paths:
      - 'scripts/ReadMeTemplate.java'
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *'

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Generate README
        run: ./scripts/generate-readme.sh
      - name: Commit changes
        if: ${{ env.COMMIT_CHANGE == 'true' }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "[BOT] Update README.md"
      - name: Publish changes
        if: ${{ env.COMMIT_CHANGE == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync to Gitee
        uses: pixta-dev/repository-mirroring-action@v1
        if: ${{ env.COMMIT_CHANGE == 'true' }}
        with:
          target_repo_url:
            git@gitee.com:Glavo/HMCL-Update.git
          ssh_private_key:
            ${{ secrets.GITEE_SYNC_BOT_PRIVATE_KEY }}
