name: Update version JSON
on:
  workflow_dispatch:
  schedule:
    - cron: '25 */6 * * *'

jobs:
  generate-update-json:
    runs-on: ubuntu-latest
    needs: generate-readme
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Update Json
        run: ./scripts/run-script.sh UpdateJson
      - name: Commit changes
        if: ${{ env.COMMIT_CHANGE == 'true' }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "[BOT] Update version json"
      - name: Publish changes
        if: ${{ env.COMMIT_CHANGE == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync to Gitee
        if: ${{ env.COMMIT_CHANGE == 'true' }}
        uses: Yikun/hub-mirror-action@v1.1
        with:
          src: github/Glavo
          dst: gitee/Glavo
          static_list: 'HMCL-Update'
          force_update: true
          debug: true
          dst_key: ${{ secrets.GITEE_SYNC_BOT_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_SYNC_BOT_TOKEN }}
          cache_path: /github/workspace/hub-mirror-cache